name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub
    - name: Update README
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: python .github/scripts/update_readme.py
    - name: Check for README.md
      id: check_readme
      run: |
        if [ -f README.md ]; then
          echo "README_EXISTS=true" >> $GITHUB_OUTPUT
        else
          echo "README_EXISTS=false" >> $GITHUB_OUTPUT
        fi
    - name: Commit and push changes
      if: steps.check_readme.outputs.README_EXISTS == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update README.md")
        
        # Try to push changes
        MAX_RETRIES=5
        RETRY_COUNT=0
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          if git push; then
            echo "Changes pushed successfully"
            exit 0
          else
            echo "Push failed. Attempting to pull and rebase..."
            git pull --rebase origin main
            RETRY_COUNT=$((RETRY_COUNT+1))
          fi
        done
        
        echo "Failed to push changes after $MAX_RETRIES attempts"
        exit 1
    - name: Report README not found
      if: steps.check_readme.outputs.README_EXISTS == 'false'
      run: |
        echo "README.md was not found. Please check the update_readme.py script output for more information."