name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Add a timeout to prevent infinite runs
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub
    - name: Update README
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: python .github/scripts/update_readme.py
    - name: Check for README changes
      id: check_changes
      run: |
        git diff --exit-code README.md || echo "README_CHANGED=true" >> $GITHUB_OUTPUT
    - name: Commit and push changes
      if: steps.check_changes.outputs.README_CHANGED == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README.md"
        git push || (git pull --rebase origin main && git push)
      env:
        GIT_AUTHOR_NAME: GitHub Action
        GIT_AUTHOR_EMAIL: action@github.com
        GIT_COMMITTER_NAME: GitHub Action
        GIT_COMMITTER_EMAIL: action@github.com